import{a as f,S as h,i as l}from"./assets/vendor-6e0bf343.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();function m(a){return a.hits.map(e=>`<div class="gallery-item">
            <a href="${e.largeImageURL}" target="_blank">
                <img src="${e.webformatURL}" alt="${e.tags}" />
            </a>
            <ul class="img-data-list">
                <li class="likes">Likes<p>${e.likes}</p></li>
                <li class="views">Views<p>${e.views}</p></li>
                <li class="comments">Comments<p>${e.comments}</p></li>
                <li class="downloads">Downloads<p>${e.downloads}</p></li>
            </ul>
        </div>`).join("")}function y(a,e){const o="43242256-64b8ba54a0ed56e09a2e1fe41",s="https://pixabay.com/api/?key="+o,t=new URLSearchParams({key:`${o}`,q:`${a}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}),r=`${s}&${t}`;return f.get(r).then(n=>n.data)}const d=document.querySelector(".form"),u=document.querySelector(".gallery"),g=new h(".gallery a",{captionsData:"alt",captionDelay:250}),i=document.getElementById("loader"),p=document.getElementById("loadMoreBtn");let c=1;async function L(){d.addEventListener("submit",async a=>{a.preventDefault();const e=d.elements.input.value;if(e!==""){i.style.display="block",u.innerHTML="",c=1;try{const o=await y(e,c);if(o.hits.length===0)l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{const s=m(o);u.innerHTML=s,g.refresh(),o.totalHits>15?p.style.display="block":p.style.display="none"}i.style.display="none"}catch{l.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}}})}async function b(){p.addEventListener("click",async()=>{const a=d.elements.input.value;i.style.display="block",c++;try{const e=await y(a,c);if(e.hits.length===0){l.info({message:"Sorry, there are no more images available.",position:"topRight"}),i.style.display="none";return}const o=m(e),s=document.createElement("div");s.innerHTML=o;const t=s.querySelectorAll("img");let r=0;t.forEach(n=>{n.onload=()=>{r++,r===t.length&&(u.innerHTML+=o,i.style.display="none",g.refresh())}})}catch{l.error({position:"topRight",message:"Sorry, there was an error loading more images. Please try again!"})}})}L();b();
//# sourceMappingURL=commonHelpers.js.map
